### ISSUE TITLE
Consider moving courses to own subdirectory

### ISSUE THREAD

**Issue by joel-huang** [OpenSUTD/course-materials#4]
See how

**Comment by randName** [comment]
not sure about it even being in the same repo as projects. I just wanted to add projects and had to download all the materials in the cloning process (a few 100mb isn't much now but it will start to stack)

**Comment by methylDragon** [comment]
Seconded. We should legitimately do it.

But then at that point, why not make this repo an **awesome list**? GitHub isn't meant to be used for storing notes either ways, innit, unless it's like jupyter notebooks, markdown files, or code...
